### ISSUE TITLE
README What is Catalyst Section re-write

### ISSUE THREAD

**Issue by nshCore** [catalyst-network/Catalyst#1104]
The catalyst Readme looks great but the contents need some love to clearly convey what we are trying to do!

**Comment by RichardLitt** [comment]
Hey, forgot about this.

How about something very simple: Catalyst [or whatever] is a collection of protocols for a distributed ledger, using a novel probablistic BFT, and allowing both storage on an IPFS-esque network and dApps.

What am I missing in this distilled definition?
