### ISSUE TITLE
As a developer I want to see amazing docs and guides

### ISSUE THREAD

**Issue by nshCore** [catalyst-network/Catalyst#1151]

**Comment by sudhirtibrewal** [comment]
More details required, as in what needs to be presented to Users.

1. Steps to setup the node
2. Link to white-paper
3. General overview

Can we minimise the numbers of repositories (currently there are 21 repositories)?

**Comment by kearneyjj1** [comment]
Status update for 05-03-2020: 

TWP - Complete, minor tweaks may be needed before deadline. Will need review for content and grammar. 
Links - Complete all checked all working in develop branch.
ReadMe - In Progress, will need some further changes for deadline with information on how to run node and other last minute information. Check back on 25-03-2020 
Others - Tokenomics currently in progress. Website to be changed.
