### ISSUE TITLE
Missing certificate / password on starting node should result in useful prompts rather than exception text

### ISSUE THREAD

**Issue by franssl** [catalyst-network/Catalyst#1200]

**Comment by franssl** [comment]
Starting a new node with no password set creates a red 'Err' print out in terminal, despite this being an expected situation. 

If no certificate is found this results in an exception being printed to the terminal rather than a useful prompt. This is a situation that is likely to occur for our users.

This is a presentation issue rather than a problem with functionality

**Comment by Xela101** [comment]
If the cert cannot be found it should auto generate a self signed cert, this doesn't work on Linux at the moment until we move to BouncyCastle..

**Comment by sudhirtibrewal** [comment]
Done as a part of another task
