### ISSUE TITLE
Remove MessageDto from Catalyst

### ISSUE THREAD

**Issue by Xela101** [catalyst-network/Catalyst#1272]
MessageDto and Channel Context in observers are heavily used by dotnetty and are not needed anymore.

**Comment by JayArrowz** [comment]
Why is DotNetty Microsoft Implementation being replaced with a unofficial LibP2P implementation. DotNetty allows us to build reliable high performance servers (nodes). Dot/Netty aimed for having a high level abstraction over network details without performance penalties as opposed to this LibP2P's 'hand crafted pipeline' processing. Buffer management/allocations are also very efficient and handled by DotNetty. 

Dot/Netty offers a well-tested production ready model for building extendable, scalable networking services whereas the latter does not

**Comment by Xela101** [comment]
We decided to go this route because we are using the unofficial LibP2P implementation for the DFS anyway(And that alone uses up a lot of network traffic for file sharing, it was already being used as a networking layer from the start by downloading candidate deltas, favorite deltas and confirmed delta's etc) and it makes more integrated to use one networking library and one keystore then two. LibP2P is suppose to provide quick, efficient reliability in its mesh network eco system. I don't want to remove any of the dotnetty stuff, I want to make that networking layer generic and swapable. Just need to do some more research into how we will do that.
