### ISSUE TITLE
As a shell user I want to have a PeerId that reflects my actual connection details

### ISSUE THREAD

**Issue by monsieurleberre** [catalyst-network/Catalyst#307]
Currently, the Shell will set the PeerId it uses to talk to a node via RPC using IPAddress.Loopback and IPEndpoint.MaxPort.
It would be better to make sure you have a true IP when connecting to a remote node and to set the Port to the actual value used to establish the TCP connection.

this needs to change
```
private static IPeerIdentifier BuildCliPeerId(IConfiguration configuration)
{
    //TODO: Handle different scenarios to get the IPAddress and Port depending
    //on you whether you are connecting to a local node, or a remote one.
    return new PeerIdentifier(configuration.GetSection("CatalystCliConfig")
        .GetSection("PublicKey").Value.ToBytesForRLPEncoding(),
    IPAddress.Loopback, IPEndPoint.MaxPort);
}
```

**Comment by sudhirtibrewal** [comment]
We are using multi address (IPv4 or IPv6)
