### ISSUE TITLE
TransferFileBytesRequest goes against the grain of the application (2 way communication not allowed)

### ISSUE THREAD

**Issue by JayArrowz** [catalyst-network/Catalyst#679]
Change logic to this:
1. RPC Client sends GetFileFromDfsRequest
2. Node will execute its handler logic (Replies to RPC client that file can be downloaded)
3. RPC client will recieve GetFileFromDfsResponse (ResponseCode = Successful + chunks)
4. Client sends DownloadChunksRequest
5. Node responds with DownloadChunksResponse

1. Rpc client sends AddFileToDfsRequest
2. Node will execute its handler logic (Replies to RPC client that file can be stored)
3. Rpc Client gets AddFileToDfsResponse (ResponseCode = Sucessful)
4. Client sends UploadFileChunksRequest 
5. Node responds UploadFileChunksResponse

**Comment by nshCore** [comment]
We should remove the socket DFS functionality and use the web3 HTTP API for this ticket.

**Comment by sudhirtibrewal** [comment]
This s not relevant anymore as this will be replaced by IPFS API
