### ISSUE TITLE
Convert to TCP from UDP

### ISSUE THREAD

**Issue by JayArrowz** [catalyst-network/Catalyst#909]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Currently in the system the Transaction object can hold many entries. However if the Transaction object and other proto objects designed to send over UDP become greater than 1472 bytes the UDP packet will fragment over the IP layer. 

See Ref: https://support.citrix.com/article/CTX115434

Currently our system does not support fragmentation 

**Describe the solution you'd like**
Use the Replaying Decoder in Netty to support UDP fragmentation.

**Describe alternatives you've considered**
- Limit the entries is a alternative
- Or we could manually chunk the packet every 1470 bytes.

**Comment by nshCore** [comment]
freezing this for now as we are not experiencing UDP packet fragmentation but something to be considered

**Comment by Xela101** [comment]
I think this will be more difficult then just using a ReplayingDecoder(Unless it supports the following), that would work for TCP but a UDP packet fragment can arrive unordered, might get dropped from an invalid checksum and won't get retried unless a custom header is built over the packet that has ordering and retry logic.

**Comment by atlassanjay** [comment]
Yeah i think a custom fragmenting & retry system would be needed on the application layer instead of IP layer allowing the packet to fragment. By having this in the application we have control over fragmentation and retries.
