### ISSUE TITLE
Prepare ERC-20 deployment contract transaction for the simulator.

### ISSUE THREAD

**Issue by tkstanczak** [catalyst-network/Catalyst#952]
1) Prepare an example ERC-20 contract to be deployed via Truffle on KVM.
2) Commit the ERC-20 contract truffle project to the source next to the KVM
3) Test ERC-20 deployment via Truffle with --verbose-rpc and copy the deployment order
    (there may be first the migration contract deployment, then some set of requests, then deployment of the 
    actual contract)
4) Prepare a transaction for simulator, that will be of KVM type and will carry the contract init code 
    (prepared from Truffle)

**Comment by nshCore** [comment]
closed in https://github.com/catalyst-network/Catalyst/pull/1167
