### ISSUE TITLE
Prepare a KVM Transaction Processor

### ISSUE THREAD

**Issue by tkstanczak** [catalyst-network/Catalyst#954]
Currently, KVM is added to the solution but the simulator / ledger cannot pass transactions for execution.
We need to define the transaction processor that will be receiving finalized transactions (no reorgs in Catalyst) and will be passing them to KVM. A separate task covers potential requirements for receipts and logs.

**Comment by nshCore** [comment]
closed in https://github.com/catalyst-network/Catalyst/pull/1167
