### ISSUE TITLE
Create KVM transaction receipt tracer.

### ISSUE THREAD

**Issue by tkstanczak** [catalyst-network/Catalyst#956]
The receipt tx tracer can be based on the standard receipt tracer from block processor/transaction processor. What is not necessarily important in Catalyst is the total gas used within the block so receipt can be simplified slightly. The receipts generated for each transaction can be passed to receipt storage,

**Comment by nshCore** [comment]
closed in https://github.com/catalyst-network/Catalyst/pull/1167
