### ISSUE TITLE
Create an eth_call style mechanism in KVM.

### ISSUE THREAD

**Issue by tkstanczak** [catalyst-network/Catalyst#957]
In order to support eth_call in EVM we set the State and Storage at a given snapshot and start processing from there. The snapshot is defined by a state root of the block for which we make a call. We are required to be able to revert any state changes after the eth_call since eth_call is not a transaction stored on the ledger and permanently changing state - it is just a test run/query via API.

We need to decide where exactly the state root of the KVM state would be stored since we do not have a notion of a block. Storing a state root after every transaction is expensive since all the tree nodes would have to be resolved (hash would have to be calculated). So it would be most natural to bind the state root with an object representing a 'state update' (a concept similar to a block in blockchain).

**Comment by nshCore** [comment]
closed in https://github.com/catalyst-network/Catalyst/pull/1167
