### ISSUE TITLE
Invoke ERC-20 smart contract methods.

### ISSUE THREAD

**Issue by tkstanczak** [catalyst-network/Catalyst#958]
Via Web3 one can discover smart contract methods for the ERC-20 contract deployed on KVM (described in the other task).

We should intercept the Web3 calls to Nethermind deployed ERC-20 and note the transaction details.
Then we should store the transaction details so these can be reused in the simulator.

This way the simulator can have a ERC-20 contract deployment followed by a series of transfers between the accounts with a non-zero balance.

For the non-zero balance accounts, the ERC-20 contract deployed may have some preallocated tokens to addresses with known private keys.

**Comment by nshCore** [comment]
closed in https://github.com/catalyst-network/Catalyst/pull/1167
