### ISSUE TITLE
Review Ethereum Patricia Tree so the KVM code does not use Keccak but Blake2b hash of Catalyst.

### ISSUE THREAD

**Issue by tkstanczak** [catalyst-network/Catalyst#960]
Patricia Tree is strongly coupled with the hash implementation. We should probably abstract the exact hash implementation and allow the calls to calculate a hash. The hash may be represented as the byte array and then the 'calculate hash' method can be delivered through an interface.

**Comment by sudhirtibrewal** [comment]
We will take this issue after testNet

**Comment by sudhirtibrewal** [comment]
We are moving to the Sparse Merkle tree, hence closing.
